### PR TITLE
Some fixes needed for me, maybe usefull for others

### PR DESCRIPTION
**Pull request by romangarcia**
I made just a few changes over you fork, which looked like the most updated.
Let me know if you find these useful

### CODE REVIEW

**Comment by mbaechler** [comment]
Thanks for you work, it's always great to receive pull requests !
If you don't mind fixing the first patch, i'll merge it right after you fix.

Regards,

**Comment by romangarcia** [comment]
Is it working good for you?

**Comment by mbaechler** [comment]
Yes, and I merged it

**Comment by mbaechler** [comment]
I need to revert the patch that remove adding recipient as "TO" field in the MimeMessage : in my experience, it delivers emails without TO header and thus break some tests we have in OBM.
Feel free to come back with some explanation about what you expected to fix with this one.

**Comment by romangarcia** [comment]
Right.

Honestly, I found while debugging GM that there were two places where the
recipients were added, and in many cases (maybe concurrence?) I would get a
MailMessage with same recipient twice.
I think I saw code involved in:
1) SmtpManager (the code I removed)
2) RctpCommand (line 50)

Regards,
Roman

**Pull request merged**
